name: pre-commit

on:
  pull_request:
  push:
    branches: [main, test-me-*]

defaults:
  run:
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    shell: bash --noprofile --norc -eo pipefail -ux {0}

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: "checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Set Up pnpm cache
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: package.json

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install direnv
        run: |
          sudo apt-get update
          sudo apt-get install -y direnv

      - name: Set up Python environment
        run: uv sync

      - name: Install Node.js dependencies
        run: pnpm install

      # allow up to three iterations for fixes to stabilize
      - name: "pre-commit: find fixes"
        id: pre-commit-fixes
        run:
          uv run pre-commit run --show-diff-on-failure --color=always
          --all-files
        continue-on-error: true

      - name: "pre-commit: check stability"
        id: pre-commit-check
        if: steps.pre-commit-fixes.outcome == 'failure'
        run:
          uv run pre-commit run --show-diff-on-failure --color=always
          --all-files

      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        if: steps.pre-commit-check.outcome == 'success'
        with:
          commit_message: "formatting, from `pre-commit run --all-files`"
